database_name: sqlite:////Users/pam/assimil/db/assimil_spanish.db
lessons_directory: /Users/pam/AssimilAudio/Sentences
html_lessons_directory: /Users/pam/assimil/lessons/html
databases_directory: /Users/pam/assimil/db
french_translation_lessons_directoy: /Users/pam/assimil/lessons/new
word_dict_logfilename: /Users/pam/assimil/word_dict_logfile.log
notes_directory: /Users/pam/assimil/lessons/notes