database_name: sqlite:////Users/pam/assimil/db/assimil_spanish_new.db
basic_audio_directory: /Users/pam/AssimilAudio/Basic
using_spanish_audio_directory: /Users/pam/AssimilAudio/UsingSpanish
html_basic_lessons_directory: /Users/pam/assimil/lessons/Basic/html
html_using_spanish_lessons_directory: /Users/pam/assimil/lessons/UsingSpanish/html
databases_directory: /Users/pam/assimil/db
french_translation_lessons_directoy: /Users/pam/assimil/lessons/new
word_dict_logfilename: /Users/pam/assimil/word_dict_logfile.log
notes_directory: /Users/pam/assimil/lessons/notes