lesson = ['Septième leçon',
'Dialogue de révision',
'Salut, ça va, beau [gosse] ? ',
 'Bien, merci... Et vous ? ',
 "Très bien, mais tutoie-moi, s'il te plaît ! ",
 'Oui, bien sûr... Je suis Javier. Et toi ? ',
 "Enchantée. Je m'appelle Montse. Tu es de Barcelone ? ",
 'Non, je vis à Barcelone mais je suis né à Madrid. ',
 'Et tu parles catalan ? ',
 'Je le lis mais je ne le parle pas très bien... ',
 "Je t'invite au cinéma, d'accord ?",
 "Euh..., merci, mais je suis patraque."]