lesson = ['Leçon cinquante-deux',
'La cuisine mexicaine',
 "- Tu ne m'as rien dit [à propos] de la cuisine mexicaine...",
 "Ou peut-être est-ce que tu n'as pas osé (osas pas) la goûter ?",
 "- Bien sûr (Par supposé) que je l'ai goûtée (je la goûtai)! J'ai surtout aimé (Me plut) le mole : c'est une sauce au (de) cacao et [aux] piments.",
 "- [Du] chocolat piquant ? Et ça ne t'a pas dégoûtée (te donna pas dégoût) ?",
 "- Pas du tout (Que va) ! C'est très bon ! L'amer va très bien avec le piquant.",
 'Les peuples précolombiens faisaient une boisson rouge avec le cacao.',
 "[C'est] pour ça [que] les conquistadors (conquérants) ont cru (crurent) qu'ils buvaient du sang !",
 '- Mais ils ne le prennent jamais sucré ?',
 "- Oui, bien sûr, de nos jours (aujourd'hui en jour) ils lui mettent aussi du sucre,",
 "mais dans la tradition indigène on ne lui ajoute pas [de] lait, seulement [de l'] eau.",
 "Nos goûters, [ça] oui (qu') ils me manquaient : un bon chocolat avec des churros...",
 "- [C'est] ça ! Pour goûter, rien ne vaut (comme) [l']Espagne !"]

exercise1_correction = ["Tu ne m'as pas dit si tu as aimé la sauce au cacao et aux piments.",
 'Tu as osé prendre du chocolat amer, piquant et sans sucre ?',
 "Pas du tout ! Ça m'a dégoûté et je ne l'ai pas goûté",
 "Eh bien c'est peut- être très bon, mais je préfère un chocolat avec des churros. ",
 'La cuisine mexicaine me manque.']