lesson = ['Leçon cinquante-six',
 'Dialogue de révision',
 "Comment est-ce que ça s'est passé ? Tu vas obtenir le poste ?",
 "Je suis convaincu que oui. J'ai passé l'entretien hier et je crois que j'ai su répondre à tout ce qu'ils m'ont demandé.",
 "Félicitations! Mais, dis-moi, quel genre de questions t'ont-ils posées ? Il y a parfois des pièges dans les entretiens, tu sais ?",
 'Pas du tout! Ils ont été très aimables et polis. 5',
 "Ils m'ont dit qu'ils allaient peut-être m'envoyer travailler à Mexico et ils ont voulu savoir si j'avais déjà été là-bas.",
 "Je leur ai répondu que je connaissais bien sûr l'Amérique latine et nous nous sommes mis à parler de la vie au Mexique.",
 "Je leur ai raconté que j'avais été partout et que j'avais même marchandé le prix d'un pull très chouette sur un marché indigène.",
 'Tu as osé leur raconter ça ?',
 'Oui, ils ont trouvé ça très drôle ! ',
 "Et tu leur as dit aussi que tu avais été dégoûté par la cuisine mexicaine, que tu n'y avais pas goûté et que tu regrettais les goûters espagnols ?",
 "Non, ça je ne l'ai surtout pas dit..."]