lesson = ['Leçon cinquante-sept',
 'Rêve ou cauchemar ?',
 "- La nuit dernière, j'ai fait (j'eus) un rêve étrange.",
 '- Ah bon (Oui) ? Tu as rêvé (Rêvas) que ton chef te souriait ?',
 "- Ne te moque [pas]... J'ai rêvé (Rêvai) que je m'[en] allais vivre au village.",
 "- Ça ressemble (semble) plus [à] un cauchemar qu'[à] un rêve.",
 "- Pourquoi ? Toi, il n'y a pas [des] jours où tu es fatigué de la circulation, du bruit et des embouteillages?",
 '- Si tu crois que la vie au (de) village est un paradis, tu te trompes (tu-es trompé):',
 "il y a (ait) peut-être moins [de] pollution, mais tu t'ennuies comme un rat mort (une huître).",
 "Mon beau-frère disait la même chose (le même) que toi. Il s'en est allé (S'alla) vivre au village et au bout de six mois il est revenu (revint).",
 "Crois-moi, rien [de] mieux qu'une grande ville.",
 '- Eh bien, que je sache, tu ne rates (ne te perds) jamais les fêtes de ton village, non ?',
 'Elles sont amusantes, je ne dis pas le contraire (que non)... Bon, et comment a fini (finit) le rêve ?',
 "- Eh bien le réveil a sonné (sonna), je me suis levé (me levai), me suis lavé (me lavai), me suis habillé (m'habillai) et je suis allé (allai) au bureau.",
 "Ah, d'ailleurs : mon (le) chef ne m'a pas souri (ne me sourit pas)."]

exercise1_correction = ["Hier soir j'ai fait un cauchemar : j'ai rêvé que je m'en allais vivre au village avec mon chef et mon beau-frère.",
 "Que je sache, tu n'as jamais raté les fêtes de ton village.",
 "Il y a peut-être moins de bruit et moins d'embouteillages mais il y a des jours où tu t'ennuies comme un rat mort.",
 "Crois-moi, tu te trompes : rien de mieux qu'une grande ville.",
 'Ne te moque pas de mes rêves.']