"""Changed serie_title -> episode_title

Revision ID: 444cfebdfe7a
Revises: c6d41ad6ee25
Create Date: 2025-04-13 14:06:49.135212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444cfebdfe7a'
down_revision: Union[str, None] = 'c6d41ad6ee25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marked_paragraphs')
    op.drop_table('user_account')
    op.drop_table('parameters')
    op.drop_table('word_dict')
    op.drop_table('lesson_sessions')
    op.drop_table('grammar_note')
    op.drop_table('paragraphs')
    op.drop_table('word_index')
    op.add_column('media', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.drop_column('media', 'series_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('series_number', sa.INTEGER(), nullable=True))
    op.drop_column('media', 'episode_number')
    op.create_table('word_index',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('lesson_nb', sa.INTEGER(), nullable=False),
    sa.Column('line_nb', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paragraphs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.INTEGER(), nullable=False),
    sa.Column('lesson_nb', sa.INTEGER(), nullable=False),
    sa.Column('line_nb', sa.INTEGER(), nullable=False),
    sa.Column('paragraph', sa.VARCHAR(), nullable=False),
    sa.Column('translation', sa.VARCHAR(), nullable=False),
    sa.Column('has_dash_dialogue', sa.BOOLEAN(), nullable=False),
    sa.Column('grammar_indexes', sa.VARCHAR(), nullable=True),
    sa.Column('data', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('lesson_nb', sa.INTEGER(), nullable=False),
    sa.Column('note_number', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('lesson_nb', sa.INTEGER(), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('errors_number', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_dict',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('tonic_accent', sa.VARCHAR(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('instance', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sa.VARCHAR(), nullable=False),
    sa.Column('parameters_version', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marked_paragraphs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paragraph', sa.VARCHAR(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('line_nb', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['lesson_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
