"""Suppresion of files names and field serie_title -> episode_title

Revision ID: c6d41ad6ee25
Revises: 
Create Date: 2025-04-12 21:05:11.413834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d41ad6ee25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('episode_title', sa.String(), nullable=True))
    op.add_column('media', sa.Column('video_filename', sa.String(), nullable=True))
    op.drop_column('media', 'series_title')
    op.drop_column('media', 'long_spanish_subtitles_file')
    op.drop_column('media', 'french_subtitles_file')
    op.drop_column('media', 'video_file')
    op.drop_column('media', 'spanish_subtitles_file')
    op.drop_column('media', 'long_french_subtitles_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('long_french_subtitles_file', sa.VARCHAR(), nullable=True))
    op.add_column('media', sa.Column('spanish_subtitles_file', sa.VARCHAR(), nullable=True))
    op.add_column('media', sa.Column('video_file', sa.VARCHAR(), nullable=True))
    op.add_column('media', sa.Column('french_subtitles_file', sa.VARCHAR(), nullable=True))
    op.add_column('media', sa.Column('long_spanish_subtitles_file', sa.VARCHAR(), nullable=True))
    op.add_column('media', sa.Column('series_title', sa.VARCHAR(), nullable=True))
    op.drop_column('media', 'video_filename')
    op.drop_column('media', 'episode_title')
    # ### end Alembic commands ###
